In [7]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers


In [4]:
from py_isear.isear_loader import IsearLoader
attributes = ['EMOT','SIT']
target = ['TROPHO','TEMPER']
loader = IsearLoader(attributes, target, True)
data = loader.load_isear('isear.csv')
data.get_data() # returns attributes
data.get_target() # returns target
data.get_freetext_content() # returns the text content of the database

['During the period of falling in love, each time that we met and 谩 especially when we had not met for a long time.',
 'When I was involved in a traffic accident.',
 'When I was driving home after  several days of hard work, there 谩 was a motorist ahead of me who was driving at 50 km/hour and 谩 refused, despite his low speeed to let me overtake.',
 'When I lost the person who meant the most to me. ',
 "The time I knocked a deer down - the sight of the animal's 谩 injuries and helplessness.  The realization that the animal was 谩 so badly hurt that it had to be put down, and when the animal 谩 screamed at the moment of death.",
 'When I did not speak the truth.',
 'When I caused problems for somebody because he could not keep the 谩 appointed time and this led to various consequences.',
 'When I got a letter offering me the Summer job that I had applied 谩 for.  ',
 'When I was going home alone one night in Paris and a man came up 谩 behind me and asked me if I was not afraid to be out alone 

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Sample training data
texts = ["This is a positive text.", "Negative sentiment here.", "I feel neutral about this."]
labels = [1, 0, 2]  # 1 for positive, 0 for negative, 2 for neutral

# Tokenize and pad the text data
tokenizer = Tokenizer(num_words=1000, oov_token="<OOV>")
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)
sequences = pad_sequences(sequences, maxlen=10, padding='post', truncating='post')
print(sequences)
input_data_list = sequences.tolist()


# Build the LSTM model
model = Sequential()
model.add(Embedding(input_dim=1000, output_dim=16, input_length=10))
model.add(LSTM(32))
model.add(Dense(3, activation='softmax'))  # Assuming you have 3 classes (positive, negative, neutral)

# Compile the model
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(input_data_list, labels, epochs=10, verbose=2)

# Now, you can use the trained model to predict labels for new input text
new_text = ["I like this product."]
new_sequence = tokenizer.texts_to_sequences(new_text)
new_sequence = pad_sequences(new_sequence, maxlen=10, padding='post', truncating='post')
predictions = model.predict(new_sequence)

# Get the predicted label (argmax of the softmax output)
predicted_label = predictions.argmax()
print(f"Predicted label: {predicted_label}")

[[ 2  3  4  5  6  0  0  0  0  0]
 [ 7  8  9  0  0  0  0  0  0  0]
 [10 11 12 13  2  0  0  0  0  0]]
Epoch 1/10
1/1 - 4s - loss: 1.0985 - accuracy: 0.3333 - 4s/epoch - 4s/step
Epoch 2/10
1/1 - 0s - loss: 1.0978 - accuracy: 0.3333 - 20ms/epoch - 20ms/step
Epoch 3/10
1/1 - 0s - loss: 1.0971 - accuracy: 0.6667 - 12ms/epoch - 12ms/step
Epoch 4/10
1/1 - 0s - loss: 1.0963 - accuracy: 0.6667 - 14ms/epoch - 14ms/step
Epoch 5/10
1/1 - 0s - loss: 1.0955 - accuracy: 0.6667 - 11ms/epoch - 11ms/step
Epoch 6/10
1/1 - 0s - loss: 1.0946 - accuracy: 0.6667 - 14ms/epoch - 14ms/step
Epoch 7/10
1/1 - 0s - loss: 1.0937 - accuracy: 0.6667 - 12ms/epoch - 12ms/step
Epoch 8/10
1/1 - 0s - loss: 1.0927 - accuracy: 0.6667 - 11ms/epoch - 11ms/step
Epoch 9/10
1/1 - 0s - loss: 1.0915 - accuracy: 1.0000 - 12ms/epoch - 12ms/step
Epoch 10/10
1/1 - 0s - loss: 1.0903 - accuracy: 1.0000 - 13ms/epoch - 13ms/step
1/1 [==============================] - 1s 643ms/step
Predicted label: 0
